# Generated by Django 3.1.2 on 2020-10-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upkeep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upkeep',
            name='maintenance',
            field=models.TextField(default='none'),
        ),
    ]
